package com.kryocore.snake.crt.entity;

public class CmsSourceTaskRule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CMS_SOURCE_TASK_RULE.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CMS_SOURCE_TASK_RULE.source_id
     *
     * @mbggenerated
     */
    private Long sourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CMS_SOURCE_TASK_RULE.source_name
     *
     * @mbggenerated
     */
    private String sourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CMS_SOURCE_TASK_RULE.agent_id
     *
     * @mbggenerated
     */
    private Long agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CMS_SOURCE_TASK_RULE.agent_ip
     *
     * @mbggenerated
     */
    private String agentIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CMS_SOURCE_TASK_RULE.task_interval
     *
     * @mbggenerated
     */
    private Long taskInterval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CMS_SOURCE_TASK_RULE.id
     *
     * @return the value of CMS_SOURCE_TASK_RULE.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CMS_SOURCE_TASK_RULE.id
     *
     * @param id the value for CMS_SOURCE_TASK_RULE.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CMS_SOURCE_TASK_RULE.source_id
     *
     * @return the value of CMS_SOURCE_TASK_RULE.source_id
     *
     * @mbggenerated
     */
    public Long getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CMS_SOURCE_TASK_RULE.source_id
     *
     * @param sourceId the value for CMS_SOURCE_TASK_RULE.source_id
     *
     * @mbggenerated
     */
    public void setSourceId(Long sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CMS_SOURCE_TASK_RULE.source_name
     *
     * @return the value of CMS_SOURCE_TASK_RULE.source_name
     *
     * @mbggenerated
     */
    public String getSourceName() {
        return sourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CMS_SOURCE_TASK_RULE.source_name
     *
     * @param sourceName the value for CMS_SOURCE_TASK_RULE.source_name
     *
     * @mbggenerated
     */
    public void setSourceName(String sourceName) {
        this.sourceName = sourceName == null ? null : sourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CMS_SOURCE_TASK_RULE.agent_id
     *
     * @return the value of CMS_SOURCE_TASK_RULE.agent_id
     *
     * @mbggenerated
     */
    public Long getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CMS_SOURCE_TASK_RULE.agent_id
     *
     * @param agentId the value for CMS_SOURCE_TASK_RULE.agent_id
     *
     * @mbggenerated
     */
    public void setAgentId(Long agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CMS_SOURCE_TASK_RULE.agent_ip
     *
     * @return the value of CMS_SOURCE_TASK_RULE.agent_ip
     *
     * @mbggenerated
     */
    public String getAgentIp() {
        return agentIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CMS_SOURCE_TASK_RULE.agent_ip
     *
     * @param agentIp the value for CMS_SOURCE_TASK_RULE.agent_ip
     *
     * @mbggenerated
     */
    public void setAgentIp(String agentIp) {
        this.agentIp = agentIp == null ? null : agentIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CMS_SOURCE_TASK_RULE.task_interval
     *
     * @return the value of CMS_SOURCE_TASK_RULE.task_interval
     *
     * @mbggenerated
     */
    public Long getTaskInterval() {
        return taskInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CMS_SOURCE_TASK_RULE.task_interval
     *
     * @param taskInterval the value for CMS_SOURCE_TASK_RULE.task_interval
     *
     * @mbggenerated
     */
    public void setTaskInterval(Long taskInterval) {
        this.taskInterval = taskInterval;
    }


    @Override
    public String toString() {
        return "CmsSourceTaskRule{" +
                "id=" + id +
                ", sourceId=" + sourceId +
                ", sourceName='" + sourceName + '\'' +
                ", agentId=" + agentId +
                ", agentIp='" + agentIp + '\'' +
                ", taskInterval=" + taskInterval +
                '}';
    }
}